### ISSUE TITLE
Request: an option for an even smaller frag?

### ISSUE THREAD

**Issue by karldw** [reifjulian/texsave#1]
Thanks for the great Stata package!

My use case might be atypical, but I often find myself wanting an even smaller fragment than `texsave ..., frag` offers. With `texsave ..., frag` I still get the begin/end table and the column type definition. Would it be possible to add a switch to avoid writing these lines? I'd be happy to contribute a pull request.

My workaround is below, but it's clunky and fragile to small changes in the content of these lines.

```stata

cap program drop write_tabular
program write_tabular
    syntax [varlist] [if] [in] using/ [, replace]
    tempfile temp1 temp2 temp3
    texsave `varlist' `if' `in' using "`temp1'", frag
    // Use filefilter to strip out some text. (\BS is a backslash)
    filefilter "`temp1'" "`temp2'", from("\BSbegin{table}[tbp] \BScentering") to("")
    filefilter "`temp2'" "`temp3'", from("\BSend{table}") to("")
    filefilter "`temp3'" "`using'", from("\BSnewcolumntype{C}{>{\BScentering\BSarraybackslash}X}") to("") `replace'
end

```

**Comment by reifjulian** [comment]
Thanks @karldw I will think about this. So basically you just want the contents of the table if sounds like. (What do you use that for, out of curiosity?)

This probably doesn't address your issue, but these days I often use the LaTeX standalone package instead of the `frag` option.

**Comment by karldw** [comment]
I hadn't seen the `standalone` package before! I think that solves a lot of my problems.


I was trying to build somewhat complicated summary stats tables, where the different parts came from different samples.

The Stata portion is something like:
* `collapse` some variables
* Replace values with rounded or formatted strings
* Label variables
* Use `texsave` to write out a table
* Repeat for a different dataset

Then the LaTeX portion was:

```latex
\begin{table}
\caption{My summary stats table}
\input{tables/sample_A.tex}
\input{tables/sample_B.tex}
\end{table}
```
