### ISSUE TITLE
Footnote width bug

### ISSUE THREAD

**Issue by Felipe-SO** [reifjulian/texsave#5]
Trying to use footnote width leads to error ``` ! Package array Error:  Illegal pream-token (\textwidth): `c' used. ``` when compiling in LaTeX.

```
clear all
cls

global outdir = "D:\Downloads"

sysuse auto, clear

tempname memhold
tempfile results
postfile `memhold' str50 Origin N Price MPG Weight using `results'
forval i = 0/1{
    local categ
	di "`categ'"
    foreach var of varlist price mpg weight{
	    summ `var' if foreign == `i'
		local mean_`var' = r(mean)
	}
	count if foreign == `i'
	post `memhold' ("`: label origin `i''") (`r(N)') ///
	(`mean_price') (`mean_mpg') (`mean_weight')
}
postclose `memhold'
use `results', clear

texsave using "${outdir}/footnote_example.tex", replace ///
	footnote("This is a footnote", width(\textwidth))

```

**Comment by reifjulian** [comment]
@Felipe-SO: Thanks for bringing this to my attention. I have updated `texsave` to address this bug. Your issue and suggested code fix prompted me to implement even more substantial edits. If you like, you can test out my edits by installing this fork:
```stata
net install texsave, from("https://raw.githubusercontent.com/reifjulian/texsave/footer") replace
```

Main changes include:
1. All footnotes now use the `\parbox{}{}` formatting you suggested. I set the footnote default width to be `\linewidth` (similar to `\textwidth` but works with landscape tables)
2. The `tabularx` columns are now aligned using `@{}`. This aligns the table contents with the `\top`, `\mid`, and `\bottomrule`, and also aligns the contents with the footnote.

Please let me know if you notice any additional issues. Otherwise I will push this to master branch in the next few weeks.

**Comment by Felipe-SO** [comment]
One small thing I've noticed is that if the footnote and the table width are narrow enough, the footnote will actually be placed to the right of the table rather than below it.
It might also be more natural for the footnote width to be the same as the table width by default rather than `\linewidth` specifically.

**Comment by reifjulian** [comment]
Do you have a minimum working example for the footnote being placed to the right of the table? For me, tables always stretch across the whole page, even with only a single variable. Eg:

```{stata}
sysuse auto.dta, clear
texsave make if price > 8000 using "table.tex", title(MPG and trunk space) footnote(Variable trunk measured in cubic feet) replace
```
![image](https://user-images.githubusercontent.com/42722121/204913407-eb1fb140-a2bc-4626-969c-defc9d97556e.png)

**Comment by Felipe-SO** [comment]
It happens when you manually set the width low enough that both the table and the footnote can fit the same line.
For example:
```
sysuse auto.dta, clear
texsave make if price > 8000 using "table.tex", title(MPG and trunk space) width(0.4\linewidth) footnote(Variable trunk measured in cubic feet, width(0.4\linewidth)) replace
```
![image](https://user-images.githubusercontent.com/68606807/204915903-12794a64-f328-4d05-ac9b-ce68c7ea2d76.png)

**Comment by reifjulian** [comment]
Hmm, I agree that is not an appealing outcome. Adding `\break` before the `\parbox...` fixes the problem, but it is not clear to me how to figure out beforehand whether or not to do that. Any ideas?

I agree with you that setting the footnote default width to be the same as the table width makes sense. I went ahead and pushed that change to this branch.

**Comment by Felipe-SO** [comment]
How about using `\\ \parbox{...}{...}` instead?
It maintains the small distance between the table and the footnote and seems to fix the issue altogether. 
(In both examples I used `\\ \parbox{...}{...}` )
![image](https://user-images.githubusercontent.com/68606807/204922188-9c802efd-765a-4d8f-9a44-b245f0613578.png) 
![image](https://user-images.githubusercontent.com/68606807/204922530-215388c0-2404-48ac-9ad0-df1e717c7fea.png)

**Comment by reifjulian** [comment]
Interesting, yes, `\\` does seem to maintain the spacing. Excellent! I made the change and updated this branch.

Any other suggestions?

**Comment by reifjulian** [comment]
These changes have been incorporated into `texsave` 1.6.0 and pushed to the master branch.
