### ISSUE TITLE
Proposal to add new align arguments

### ISSUE THREAD

**Issue by tudorschlanger** [reifjulian/texsave#8]
Hi Julian, thank you for the package, it's been very useful! 

At the moment, the user can set align to "C" which wraps the lines. 
Can I suggest adding two more arguments to the align option? I am thinking of "L" and "R", which would take the following forms in the table environment : 

    \newcolumntype{R}{>{\raggedleft\arraybackslash}X}
    \newcolumntype{L}{>{\raggedright\arraybackslash}X}
    
Thanks again!

**Comment by reifjulian** [comment]
@tudorschlanger Glad to hear you find `texsave` useful! Adding these arguments should be straightforward. I have not seen them used before. Are you aware of any standards for how these two arguments are typically named? The [one example](https://stackoverflow.com/questions/72460770/line-cut-in-tabularx) I found online swaps your definition of `L` and `R`.

**Comment by tudorschlanger** [comment]
If you go to this page from the [Overleaf documentation](https://www.overleaf.com/learn/latex/Text_alignment), you will see a reference guide table at the end of the page. This table shows that the commands for alignment right are "flush right" and "raggedleft". I believe this is standard.

**Comment by reifjulian** [comment]
Thanks, I agree that this Overleaf documentation is consistent with your suggestion. I have pushed these new options to the development version of `texsave` and its help file. Please try it out and let me know if it does what you were looking for. You can install it using the following command:

```stata
net install texsave, from("https://raw.githubusercontent.com/reifjulian/texsave/development") replace
```

**Comment by tudorschlanger** [comment]
Yes, it does what it needed! Thank you for the prompt code change!

**Comment by reifjulian** [comment]
These changes have now been pushed to the master branch, and will be available on SSC shortly.
